[package]
name = "disk-queue"
version = "0.1.0"
edition = "2021"
authors = ["Armin Primadi <aprimadi@gmail.com>"]

[dependencies]
memmap = "0.7"

[dev-dependencies]
criterion = "0.3"
rand = "0.8"

[[bench]]
name = "write"
harness = false

[[bench]]
name = "read"
harness = false

